apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "honeytrap.fullname" . }}-config
data:
  config.toml: |
{{ .Values.config.configToml | indent 4 }}

  base-policies.yaml: |
{{ .Values.config.policies.base | indent 4 }}

  high-risk.yaml: |
{{ .Values.config.policies.highRisk | indent 4 }}
